# Generated by Django 4.2.4 on 2023-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hability',
            options={'verbose_name': 'Hability', 'verbose_name_plural': 'Habilities'},
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(),
        ),
    ]
