# Generated by Django 4.2.4 on 2023-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_hability_options_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='hability',
            name='image',
            field=models.ImageField(null=True, upload_to='hability'),
        ),
    ]
