# Generated by Django 4.2.4 on 2023-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_hability_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('types', models.CharField(choices=[('linguagem', 'LP'), ('framework', 'FW')], max_length=10)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.DeleteModel(
            name='Hability',
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
