# Generated by Django 4.2.4 on 2023-10-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_skill_rename_projects_project_delete_hability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='types',
            field=models.CharField(choices=[('Front-end', 'F'), ('Back-end', 'B'), ('Desktop', 'D'), ('AI/ML', 'ML'), ('CI/CD', 'CC'), ('UI/UX', 'U')], max_length=10),
        ),
    ]
