# Generated by Django 4.2.4 on 2023-10-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_skill_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(null=True),
        ),
    ]
