# Generated by Django 4.2.4 on 2024-02-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_project_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cv",
            field=models.FileField(null=True, upload_to="cvs/"),
        ),
    ]
