# Generated by Django 4.2.4 on 2024-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_user_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
