# Generated by Django 4.2.4 on 2024-02-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_user_cv_alter_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
