# Generated by Django 4.2.4 on 2024-02-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_remove_user_cv_remove_user_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="types",
            field=models.CharField(
                choices=[
                    ("Front-end", "F"),
                    ("Back-end", "B"),
                    ("Desktop", "D"),
                    ("AI/ML", "ML"),
                    ("UI/UX", "U"),
                    ("other", "O"),
                ],
                max_length=10,
            ),
        ),
    ]
