# Generated by Django 4.2.4 on 2024-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_alter_skill_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
